/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package itsalesgui2;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Samantha
 */
public class MainForm extends javax.swing.JFrame {

    ArrayList<DesktopClass> myDesktopInfo = new ArrayList<DesktopClass>();
    
    ArrayList<LaptopClass> myLaptopInfo = new ArrayList<LaptopClass>();
    
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        ButtonGroup bgroup = new ButtonGroup();
        bgroup.add(Desktopbutton);
        bgroup.add(Laptopbutton);
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DisplayArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        LaptopDisplayArea = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        LaptopDisplay = new javax.swing.JButton();
        Close_panel = new javax.swing.JPanel();
        Close_label = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        minimize_label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Desktopbutton = new javax.swing.JRadioButton();
        Laptopbutton = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        CompIDtxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Speedtxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Ramtxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        HDDtxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmbMonitor = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        Pricetxt = new javax.swing.JTextField();
        Addbutton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        DisplayArea.setEditable(false);
        DisplayArea.setColumns(20);
        DisplayArea.setRows(5);
        jScrollPane1.setViewportView(DisplayArea);

        LaptopDisplayArea.setEditable(false);
        LaptopDisplayArea.setColumns(20);
        LaptopDisplayArea.setRows(5);
        jScrollPane2.setViewportView(LaptopDisplayArea);

        jButton2.setText("Display Desktop Information");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        LaptopDisplay.setText("Display Laptop Information");
        LaptopDisplay.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LaptopDisplay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LaptopDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaptopDisplayActionPerformed(evt);
            }
        });

        Close_panel.setBackground(new java.awt.Color(255, 204, 255));
        Close_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Close_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Close_panelMouseExited(evt);
            }
        });

        Close_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Close_label.setForeground(new java.awt.Color(204, 255, 255));
        Close_label.setText("    X");
        Close_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Close_labelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Close_labelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Close_labelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Close_panelLayout = new javax.swing.GroupLayout(Close_panel);
        Close_panel.setLayout(Close_panelLayout);
        Close_panelLayout.setHorizontalGroup(
            Close_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Close_panelLayout.createSequentialGroup()
                .addComponent(Close_label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Close_panelLayout.setVerticalGroup(
            Close_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Close_panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Close_label, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 204, 255));

        minimize_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        minimize_label.setForeground(new java.awt.Color(204, 255, 255));
        minimize_label.setText("   -");
        minimize_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimize_labelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(minimize_label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(minimize_label, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LaptopDisplay)
                .addGap(136, 136, 136))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 79, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Close_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Close_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LaptopDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Computer Menu");

        Desktopbutton.setBackground(new java.awt.Color(255, 204, 255));
        Desktopbutton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Desktopbutton.setSelected(true);
        Desktopbutton.setText("Desktop");
        Desktopbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DesktopbuttonActionPerformed(evt);
            }
        });

        Laptopbutton.setBackground(new java.awt.Color(255, 204, 255));
        Laptopbutton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Laptopbutton.setText("Laptop");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Computer ID:");

        CompIDtxt.setBackground(new java.awt.Color(204, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Processor Speed (GHz):");

        Speedtxt.setEditable(false);
        Speedtxt.setBackground(new java.awt.Color(204, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("RAM (MB):");

        Ramtxt.setBackground(new java.awt.Color(204, 255, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Harddisk Size (GB):");

        HDDtxt.setBackground(new java.awt.Color(204, 255, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Monitor Type:");

        cmbMonitor.setBackground(new java.awt.Color(255, 153, 255));
        cmbMonitor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LCD", "LED", "CRT", " " }));
        cmbMonitor.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Price:");

        Pricetxt.setBackground(new java.awt.Color(204, 255, 255));

        Addbutton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Addbutton.setText("Add");
        Addbutton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Addbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbuttonActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itsalesgui2/icons8-ipad-like-65.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Speedtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ramtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HDDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pricetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(Addbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CompIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Desktopbutton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Laptopbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Laptopbutton)
                            .addComponent(Desktopbutton)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CompIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Speedtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ramtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HDDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pricetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Addbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbuttonActionPerformed
        // TODO add your handling code here:
        
        if(CompIDtxt.getText().trim().length() != 0 && Speedtxt.getText().trim().length() != 0 && HDDtxt.getText().trim().length() != 0 && Ramtxt.getText().trim().length() != 0
                && HDDtxt.getText().trim().length() != 0 && Pricetxt.getText().trim().length() != 0){
            if(Desktopbutton.isSelected()){
                DesktopClass myNewDesktop = new DesktopClass();
                myNewDesktop.sComputerID = String.valueOf(CompIDtxt.getText());
                myNewDesktop.dProcessorSpeed = Double.parseDouble(Speedtxt.getText());
                myNewDesktop.RAM = Integer.parseInt(Ramtxt.getText());
                myNewDesktop.dPrice = Double.parseDouble(Pricetxt.getText());
                myNewDesktop.Harddisk = Integer.parseInt(HDDtxt.getText());
                myNewDesktop.Monitor = cmbMonitor.getSelectedItem().toString();
                
                JOptionPane.showMessageDialog(this, "Information has been added successfully !", "Done", JOptionPane.CLOSED_OPTION);
                
                myDesktopInfo.add(myNewDesktop);
                
            }else if(Laptopbutton.isSelected()){
                LaptopClass myNewLaptop = new LaptopClass();
                myNewLaptop.sComputerID = String.valueOf(CompIDtxt.getText());
                myNewLaptop.dProcessorSpeed = Double.parseDouble(Speedtxt.getText());
                myNewLaptop.RAM = Integer.parseInt(Ramtxt.getText());
                myNewLaptop.dPrice = Double.parseDouble(Pricetxt.getText());
                myNewLaptop.Harddisk = Integer.parseInt(HDDtxt.getText());
                
                JOptionPane.showMessageDialog(this, "Information has been added successfully !", "Done", JOptionPane.CLOSED_OPTION);

                myLaptopInfo.add(myNewLaptop);
            }
        }else{
                JOptionPane.showMessageDialog(this, "Empty Fields!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_AddbuttonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int iDesktopSize = myDesktopInfo.size();
        String sDisplay = "";
        
        if(iDesktopSize != 0){
            for(int i = 0; i < iDesktopSize; i++){
                sDisplay = sDisplay + "++++++++ Desktop Information ++++++++";
                sDisplay = sDisplay + myDesktopInfo.get(i).getComputerInfo();
            }
        }else{
            JOptionPane.showMessageDialog(null, "There is NO Desktop Information!");
        }
        
        DisplayArea.setText(sDisplay);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void DesktopbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesktopbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DesktopbuttonActionPerformed

    private void LaptopDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaptopDisplayActionPerformed
        // TODO add your handling code here:
        int iDesktopSize = myLaptopInfo.size();
        String sDisplay = "";
        
        if(iDesktopSize != 0){
            for(int i = 0; i < iDesktopSize; i++){
                sDisplay = sDisplay + "++++++++ Laptop Information +++++++++";
                sDisplay = sDisplay + myLaptopInfo.get(i).getComputerInfo();
            }
        }else{
            JOptionPane.showMessageDialog(null, "There is NO Desktop Information!");
        }
        
        LaptopDisplayArea.setText(sDisplay);
    }//GEN-LAST:event_LaptopDisplayActionPerformed

    private void Close_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close_panelMouseEntered
        // TODO add your handling code here:
        Close_panel.setBackground(new Color(255,0,0));
    }//GEN-LAST:event_Close_panelMouseEntered

    private void Close_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close_panelMouseExited
        // TODO add your handling code here:
        Close_panel.setBackground(new Color(255,204,255));
    }//GEN-LAST:event_Close_panelMouseExited

    private void Close_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close_labelMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_Close_labelMouseClicked

    private void Close_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close_labelMouseEntered
        // TODO add your handling code here:
        Close_label.setBackground(new Color(255,0,0));
    }//GEN-LAST:event_Close_labelMouseEntered

    private void Close_labelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close_labelMouseExited
        // TODO add your handling code here:
        Close_label.setBackground(new Color(255,204,255));
    }//GEN-LAST:event_Close_labelMouseExited

    private void minimize_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_labelMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimize_labelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addbutton;
    private javax.swing.JLabel Close_label;
    private javax.swing.JPanel Close_panel;
    private javax.swing.JTextField CompIDtxt;
    private javax.swing.JRadioButton Desktopbutton;
    private javax.swing.JTextArea DisplayArea;
    private javax.swing.JTextField HDDtxt;
    private javax.swing.JButton LaptopDisplay;
    private javax.swing.JTextArea LaptopDisplayArea;
    private javax.swing.JRadioButton Laptopbutton;
    private javax.swing.JTextField Pricetxt;
    private javax.swing.JTextField Ramtxt;
    private javax.swing.JTextField Speedtxt;
    private javax.swing.JComboBox<String> cmbMonitor;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel minimize_label;
    // End of variables declaration//GEN-END:variables
}
